name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest
    steps:
      # 1. Check-out repository
      - name: Check-out repository
        uses: actions/checkout@v4

      # 2. Install npm dependencies
      - name: Use Node.js from .nvmrc
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"

      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run build

      # 6. Upload the binary as an artifact
      - uses: actions/upload-artifact@v2
        with:
          name: binary
          path: "out/continue-binary"
